version: '3'
services:
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - ./cms/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=directus
     - MYSQL_PASSWORD=directus
     - MYSQL_DATABASE=directus
     - MYSQL_CHARSET=utf8_general_ci
    ports:
      - 3306:3306
    # healthcheck:
    #   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 20

  cache:
    image: redis:6

  directus:
    image: directus/directus:10.6.1
    ports:
      - 8055:8055
    volumes:
      - ./cms/uploads:/directus/uploads
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    depends_on:      
      - database
      - cache
      # database:
      #   condition: service_healthy
      #   restart: true
      # cache:
      #   condition: service_started
      #   restart: false
    environment:
      KEY: '56a30262-81f6-45ee-90e2-1a15de0d0857'
      SECRET: '0fc2dce6-945c-4af4-adb0-eed842c76117'

      DB_CLIENT: 'mysql'
      DB_HOST: 'database'
      DB_PORT: '3306'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_AUTO_PURGE: 'true'
      IMPORT_IP_DENY_LIST: '' # REMOVE FOR PRODUCTION
      REDIS: 'redis://cache:6379'
      WEBSOCKETS_ENABLED: 'false'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'andre'
      TELEMETRY: 'false'
  
  webserver:
    build: 
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    depends_on:      
      - directus