version: '3'

networks:
  loki:

services:
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - ./cms/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=directus
     - MYSQL_PASSWORD=directus
     - MYSQL_DATABASE=directus
     - MYSQL_CHARSET=utf8_general_ci
    ports:
      - 3306:3306
    networks:
      - loki

  cache:
    image: redis:6
    networks:
      - loki

  directus:
    image: directus/directus:10.6.1
    ports:
      - 8055:8055
    volumes:
      - ./cms/uploads:/directus/uploads
    depends_on:      
      - database
      - cache
    environment:
      KEY: '56a30262-81f6-45ee-90e2-1a15de0d0857'
      SECRET: '0fc2dce6-945c-4af4-adb0-eed842c76117'

      DB_CLIENT: 'mysql'
      DB_HOST: 'database'
      DB_PORT: '3306'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_AUTO_PURGE: 'true'
      IMPORT_IP_DENY_LIST: '' # REMOVE FOR PRODUCTION
      REDIS: 'redis://cache:6379'
      WEBSOCKETS_ENABLED: 'false'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'
      TELEMETRY: 'false'
    networks:
      - loki
  
  webserver:
    build: 
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    links:
      - directus
      - promtail
      - grafana
      - alertmanager
      - prometheus
      - loki

    depends_on:      
      - directus
    networks:
      - loki
  
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./devops/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - loki
  
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    volumes:
      - "./devops/loki:/mnt/config"  
    command: -config.file=/mnt/config/loki-config.yaml
    networks:
      - loki
  
  promtail:
    image: grafana/promtail
    volumes:
      - "./devops/promtail:/mnt/config"
      - "/var/lib/docker/containers:/var/lib/docker/containers"
    command: -config.file=/mnt/config/promtail-config.yaml
    networks:
      - loki

  grafana:
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_USERS_ALLOW_SIGN_UP=false
    image: grafana/grafana:latest
    volumes:
      - "./devops/grafana/grafana_data:/var/lib/grafana"
    ports:
      - "3000:3000"
    networks:
      - loki

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    volumes:
      - ./devops/alertmanager/alertmanager.yml:/etc/alertmanager/config.yml
    ports:
      - 9093:9093
    networks:
      - loki